export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
    "A fairytale wedding in a magical forest with talking animals as guests.",
    "A romantic gondola ride through the canals of a sunken city.",
    "A marriage proposal under the starry sky with a comet streaking by.",
    "A beach wedding with dolphins jumping in the background.",
    "A couple's journey through time, from their first date to old age.",
    "A volcanic island with lava flowing into a bioluminescent ocean.",
    "A floating city in the clouds with cascading waterfalls.",
    "A mysterious underground cavern filled with glowing crystals.",
    "A frozen wasteland with towering ice sculptures.",
    "A serene meadow with a path leading to a hidden temple.",
    "A colossal statue of a phoenix rising from the ashes.",
    "A serene temple hidden deep within a mystical forest.",
    "A modern reinterpretation of the Great Wall of China.",
    "A city square with a monument to celebrate peace and unity.",
    "A steampunk version of the Statue of Liberty.",
    "A tranquil waterfall in the heart of a bioluminescent forest.",
    "A field of giant mushrooms under a starry sky.",
    "A crystal-clear lake surrounded by vibrant, floating islands.",
    "A desert oasis with neon-colored cacti and flamingos.",
    "A floating island made entirely of interconnected trees.",
    "An elegant, futuristic yacht cruising through a city's waterways.",
    "A retro-inspired hoverbike speeding through a neon-lit metropolis.",
    "A fantastical airship that doubles as a mobile garden.",
    "A vintage car with wings, ready for takeoff.",
    "A submarine shaped like a mythical sea creature.",
    "An army of robotic soldiers marching through a digital battlefield.",
    "A post-apocalyptic tank covered in graffiti.",
    "A medieval siege with catapults and a dragon in the distance.",
    "A band of futuristic rebels preparing for a cyber war.",
    "A scene of truce between two alien species amidst the ruins of a city.",
    "A scene from a sci-fi movie with an otherworldly alien species.",
    "A portrait of a famous historical figure in a contemporary setting.",
    "A film poster for a never-before-seen epic adventure.",
    "A cosmic showdown between two iconic movie monsters.",
    "A modern-day reimagining of a classic film poster.",
    "A whirlwind of colors and shapes in an abstract art gallery.",
    "A dreamscape with geometric patterns floating in the sky.",
    "An abstract representation of the concept of time.",
    "A surreal digital cityscape with gravity-defying architecture.",
    "A chaotic blend of nature and technology in a digital painting.",
    "A futuristic cyberpunk cityscape with neon signs and holographic billboards.",
    "A digital hacker's lair hidden in the heart of a virtual realm.",
    "An AI-controlled utopia where machines and humans coexist seamlessly.",
    "A digital deity ruling over a realm of binary code and data streams.",
    "A dystopian future where AI-controlled drones roam a desolate metropolis.",
    "A pixelated hero on a quest to rescue the princess from a dragon's lair.",
    "A virtual reality gaming arena with players battling in a sci-fi setting.",
    "A tabletop board game brought to life in a magical forest.",
    "A retro arcade filled with classic video game characters.",
    "An otherworldly chess match with sentient pieces.",
    "A mischievous kitten playing with a ball of yarn in a sunbeam.",
    "A loyal dog and its owner sharing a heartwarming moment.",
    "A colorful aviary with exotic birds in a lush rainforest.",
    "A friendly robot companion designed to be the perfect pet.",
    "A family of penguins waddling across the icy tundra.",
    "A whimsical animation studio with characters coming to life.",
    "A living 2D character stepping into a 3D world.",
    "A stop-motion animation set with claymation creatures.",
    "A futuristic animation software creating scenes in real-time.",
    "A scene from a classic Disney-style fairytale.",
    "A field of vibrant wildflowers stretching to the horizon.",
    "A floral paradise with giant blossoms in surreal colors.",
    "A flower market bustling with people and colorful arrangements.",
    "An enchanted forest with bioluminescent, glowing flowers.",
    "A bouquet of rare, otherworldly flowers with magical properties.",
    "A cloud city floating high above the Earth.",
    "A stormy sky with lightning illuminating menacing cloud formations.",
    "A serene, cotton candy sunset in a sky filled with fluffy clouds.",
    "A peaceful dream world with fluffy clouds as stepping stones.",
    "A surreal dreamscape where clouds take on fantastical shapes.",
    "A lunar base on the moon's surface with astronauts exploring.",
    "A moonlit landscape with a hidden lunar colony.",
    "A fantastical scene of people living on the moon's surface.",
    "A mysterious alien city on the far side of the moon.",
    "A retro-futuristic moon station with rocket ships taking off.",
    "A breathtaking view of the Milky Way galaxy from an alien planet.",
    "An interstellar highway with spaceships traveling among the stars.",
    "A cosmic metropolis at the heart of the Milky Way.",
    "A wormhole opening to a distant galaxy in deep space.",
    "A space colony orbiting a distant star in the Milky Way.",
    "A space station orbiting Saturn with a stunning ring system.",
    "A visit to Saturn's moon Titan with its methane lakes.",
    "An epic space battle near the asteroid belt in our solar system.",
    "A robotic explorer on a mission to Pluto at the edge of the solar system.",
    "A futuristic research facility orbiting the sun.",
    "A close-up view of the sun's turbulent surface.",
    "A solar flare erupting from the sun's corona.",
    "A civilization harnessing the power of the sun for energy.",
    "A spacecraft on a mission to explore the sun's mysteries.",
    "A sunset on an alien planet orbiting a binary star system.",
    "A field of dandelions being carried away by the wind.",
    "A sunflower garden with giant, glowing blossoms.",
    "A close-up of a sunflower with intricate details.",
    "Dandelions and sunflowers coexisting in a surreal meadow.",
    "A whimsical world where dandelions transform into hot air balloons.",
    "A pristine tropical beach with palm trees and clear turquoise waters.",
    "A hidden cove with bioluminescent creatures in the shallows.",
    "A beach volleyball tournament with teams of mythical creatures.",
    "A surreal beachscape with sandcastles that defy gravity.",
    "A beachside carnival with rides and colorful kiosks.",
    "An underwater city of merfolk in a coral reef metropolis.",
    "A submarine exploring the deepest trench of the ocean.",
    "A group of playful dolphins interacting with human divers.",
    "An aquatic alien planet with bioluminescent marine life.",
    "An underwater concert with sea creatures playing musical instruments.",
    "A tranquil, bioluminescent sea cave with hidden treasures.",
    "A fierce battle between pirates and sea monsters on the open ocean.",
    "An underwater metropolis beneath the waves.",
    "A beautiful shipwreck covered in colorful coral.",
    "A massive sea turtle carrying a world of coral on its back.",
    "An autumn forest with leaves of vibrant reds and oranges.",
    "A springtime garden with flowers in full bloom.",
    "A surreal blend of autumn and spring in a single landscape.",
    "A magical doorway that transitions between autumn and spring.",
    "A forest where the changing of seasons happens in real-time.",
    "A colony on Mars with advanced terraforming technology.",
    "A sandstorm on the Martian surface as explorers take cover.",
    "A futuristic Mars rover on a mission to discover ancient life.",
    "A bustling Martian city with its own unique architecture.",
    "A terraformed Mars with oceans and forests.",
    "A vibrant street parade during a cultural festival.",
    "A lantern-lit celebration under a starry night sky.",
    "A masked carnival with performers in elaborate costumes.",
    "A fireworks display over a city skyline during a New Year's celebration.",
    "A festival of lights illuminating a historic town square.",
    "An open book with fantastical worlds spilling from its pages.",
    "A cozy library with books of all genres reaching to the ceiling.",
    "A writer's desk with scattered pages and a typewriter.",
    "A literary masterpiece coming to life with characters stepping out of the book.",
    "A magical quill pen inscribing a new story in the air.",
    "A famous writer signing books for an adoring crowd.",
    "A reclusive author in a hidden forest cabin finding inspiration.",
    "A writer's workshop with authors from different eras collaborating.",
    "A writer's journey from the first draft to a published novel.",
    "A writer surrounded by floating words and ideas.",
    "A poet under a moonlit sky composing verses in the sand.",
    "A spoken word poetry slam with passionate performances.",
    "A library filled with shelves of poetry collections from different cultures.",
    "A live poetry reading in a candlelit coffeehouse.",
    "A poet's emotions transformed into a swirling vortex of words.",
    "A grand concert hall filled with symphony orchestra musicians.",
    "A jazz club with a saxophonist playing in a smoky atmosphere.",
    "A futuristic music festival with holographic performers.",
    "A rock band on stage with fans cheering in the audience.",
    "A serene forest with musical notes floating in the air.",
    "A time-traveler exploring ancient ruins in a lost city.",
    "A museum exhibit showcasing artifacts from an ancient civilization.",
    "A historian's desk covered in maps, scrolls, and artifacts.",
    "A reenactment of a historic battle with period-accurate costumes.",
    "A time machine revealing glimpses of the past.",
    "A treasure hunter discovering a trove of ancient relics in a hidden cave.",
    "An archaeologist carefully excavating a burial site.",
    "A collection of antique artifacts from different eras.",
    "A steampunk archaeologist uncovering a mysterious artifact.",
    "A library of ancient scrolls and manuscripts.",
    "A bustling street in a futuristic metropolis with flying cars.",
    "A rooftop garden in the heart of a vibrant urban jungle.",
    "A bustling marketplace with street food vendors and vibrant colors.",
    "A city park with people enjoying a sunny day.",
    "A hidden speakeasy in a vibrant city district.",
    "A tranquil beach with crystal-clear waters and a gentle breeze.",
    "A coastal town with colorful fishing boats lining the shore.",
    "A beach party with bonfires and live music.",
    "A secluded cove with tide pools and unique marine life.",
    "A surfer catching a giant wave at sunrise.",
    "A cityscape at night with skyscrapers illuminated by neon lights.",
    "A rainy night in the city with reflections in puddles.",
    "A futuristic city skyline with holographic billboards.",
    "A bustling city street with a mixture of cultures and languages.",
    "A rooftop bar with panoramic views of a sparkling city at night.",
    "A classic film noir scene with dramatic shadows and intrigue.",
    "A vintage photograph of a bygone era in black and white.",
    "A moody forest with stark black and white contrast.",
    "A world transitioning from grayscale to vibrant color.",
    "A grayscale steampunk cityscape with intricate details.",
    "A hot air balloon festival with colorful balloons filling the sky.",
    "A child's birthday party with balloons and confetti.",
    "A balloon artist creating intricate sculptures at a fair.",
    "A whimsical world where balloons are used as transportation.",
    "A hot air balloon voyage over a surreal landscape.",
    "A fantastical 3D animation of a mythical creature in flight.",
    "A complex 3D animation of a futuristic cityscape.",
    "A 3D animation of a sci-fi space battle.",
    "A 3D character exploring a virtual reality world.",
    "A 3D animation of a futuristic vehicle in motion.",
    "A 4D animation with sensory effects, like scent and motion.",
    "A 4D animation of an underwater adventure with splashes and mist.",
    "A 4D animated ride through a prehistoric world with tactile feedback.",
    "A 4D animation of a haunted house with spooky surprises.",
    "A 4D animation of a thrilling roller coaster experience.",
    "An anime character in a traditional Japanese garden.",
    "A group of anime heroes on an epic quest.",
    "A futuristic cyberpunk city in the style of anime.",
    "A magical girl transforming in a burst of sparkles and light.",
    "A serene anime village with cherry blossom trees.",
];